### PR TITLE
Fix query encoding

### PR DESCRIPTION
**Pull request by 95th**
Fixes https://github.com/alexliesenfeld/httpmock/issues/56

### CODE REVIEW

**Comment by alexliesenfeld** [comment]
Thanks for providing this pull request! Looks good so far. I'll merge it into current dev branch. It will probably land in a release soon.

**Comment by StarpTech** [comment]
@95th, thanks for addressing it.

**Comment by StarpTech** [comment]
@alexliesenfeld could you make a release?

**Comment by alexliesenfeld** [comment]
Hi @StarpTech . Yes, the release is currently waiting for #63 to get merged into master. It should be merged very soon.

**Pull request merged**
